### PR TITLE
Features/llama3.1

### LINKED ISSUE #27: Add support for llama 3.1 8b
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your proposal related to a problem or functionality gap?

_No response_

### Describe your proposal

Llama 3.1 should be a model option

### Describe alternatives you've considered

_No response_

### I'm part of a Project Team

_No response_

### Anything else?

_No response_

### Are you willing to contribute to developing this feature?

✅ Yes, me or my team intend to do the development.

### PR DESCRIPTION
**Pull request by kuraisle**
## Pull Request Contents

| |
|-|
♻️ Refactor
✨ Feature
🦋 Bug Fix

## Description

The latest llama 8b model is meant to seriously outperform llama 3. I've added it to the models usable in the API.

As part of this, I've edited the way local models are loaded. This unpacks a dictionary as arguments to hf_hub_download, meaning we can pass other kwargs to load the model if necessary.

The quantized llama3.1 models wouldn't work with llama-cpp-python 0.2.69. I guess the GGUF format has changed a bit between versions. Upgrading llama-cpp-python got these to load, but there's an issue with using these versions of llama-cpp-python and the haystack integration. Adding the special end of turn token to the prompt fixed this.

## Related Issues or other material

- [X] This PR relates to one or more issues, detailed below

- Related Issue #27 
- Closes #27 

## ✅ Added/updated tests?

- [X] This PR contains relevant tests
  - Or doesn't need to per the below explanation

We still need tests

- [X] I've completed all **actions** and **tasks** detailed in the PR Template

### CODE REVIEW

**Comment by Karthi-DStech** [comment]
Hi James, 

When I tried to clone your branch and run lettuce, I am getting this error. 

`(base) Karthikeyans-MacBook-Air-2:Carrot-Assistant karthik$ streamlit run ui.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.180:8501

2024-08-13 10:18:04.378 Uncaught app exception
Traceback (most recent call last):
  File "/Users/karthik/anaconda3/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/Users/karthik/lettuce-features-llama3.1/Carrot-Assistant/ui.py", line 7, in <module>
    pg.run()
  File "/Users/karthik/anaconda3/lib/python3.11/site-packages/streamlit/navigation/page.py", line 286, in run
    exec(code, module.__dict__)
  File "/Users/karthik/lettuce-features-llama3.1/Carrot-Assistant/text_input.py", line 32, in <module>
    result_stream: sseclient.SSEClient = make_api_call(names_list, skip_llm, vocab_id)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karthik/lettuce-features-llama3.1/Carrot-Assistant/ui_utilities.py", line 104, in make_api_call
    response = requests.post(url, headers=headers, json=data, stream=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karthik/anaconda3/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/Users/karthik/anaconda3/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karthik/anaconda3/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/karthik/anaconda3/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type EmbeddingModel is not JSON serializable`

**Comment by kuraisle** [comment]
> 2024-08-13 10:18:04.378 Uncaught app exception Traceback (most recent call last): File "/Users/karthik/anaconda3/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script exec(code, module.**dict**) File "/Users/karthik/lettuce-features-llama3.1/Carrot-Assistant/ui.py", line 7, in pg.run() File "/Users/karthik/anaconda3/lib/python3.11/site-packages/streamlit/navigation/page.py", line 286, in run exec(code, module.**dict**) File "/Users/karthik/lettuce-features-llama3.1/Carrot-Assistant/text_input.py", line 32, in result_stream: sseclient.SSEClient = make_api_call(names_list, skip_llm, vocab_id) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/karthik/lettuce-features-llama3.1/Carrot-Assistant/ui_utilities.py", line 104, in make_api_call response = requests.post(url, headers=headers, json=data, stream=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/api.py", line 115, in post return request("post", url, data=data, json=json, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 575, in request prep = self.prepare_request(req) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request p.prepare( File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/models.py", line 371, in prepare self.prepare_body(data, files, json) File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/models.py", line 511, in prepare_body body = complexjson.dumps(json, allow_nan=False) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/json/**init**.py", line 238, in dumps **kw).encode(obj) ^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/json/encoder.py", line 200, in encode chunks = self.iterencode(o, _one_shot=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/json/encoder.py", line 258, in iterencode return _iterencode(o, 0) ^^^^^^^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/json/encoder.py", line 180, in default raise TypeError(f'Object of type {o.**class**.**name**} ' TypeError: Object of type EmbeddingModel is not JSON serializable`

This error is because the enum I am using to select valid embedding models can't be expressed as JSON, so can't be sent as an API request. The `LLMModel` enum is JSON serializable because it also inherits from `str`, but the EmbeddingModel is a tuple of values.

**Comment by Karthi-DStech** [comment]
Hi James,

I attempted to remove embeddings.py scripts and execute the code. Then it downloads the new Llama model and returns the output in the GUI. 

I guess there is some problem in embeddings.py. Does the scripts work in your local machine James?

**Comment by Karthi-DStech** [comment]
> > 2024-08-13 10:18:04.378 Uncaught app exception Traceback (most recent call last): File "/Users/karthik/anaconda3/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script exec(code, module.**dict**) File "/Users/karthik/lettuce-features-llama3.1/Carrot-Assistant/ui.py", line 7, in pg.run() File "/Users/karthik/anaconda3/lib/python3.11/site-packages/streamlit/navigation/page.py", line 286, in run exec(code, module.**dict**) File "/Users/karthik/lettuce-features-llama3.1/Carrot-Assistant/text_input.py", line 32, in result_stream: sseclient.SSEClient = make_api_call(names_list, skip_llm, vocab_id) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/karthik/lettuce-features-llama3.1/Carrot-Assistant/ui_utilities.py", line 104, in make_api_call response = requests.post(url, headers=headers, json=data, stream=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/api.py", line 115, in post return request("post", url, data=data, json=json, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 575, in request prep = self.prepare_request(req) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request p.prepare( File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/models.py", line 371, in prepare self.prepare_body(data, files, json) File "/Users/karthik/anaconda3/lib/python3.11/site-packages/requests/models.py", line 511, in prepare_body body = complexjson.dumps(json, allow_nan=False) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/json/**init**.py", line 238, in dumps **kw).encode(obj) ^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/json/encoder.py", line 200, in encode chunks = self.iterencode(o, _one_shot=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/json/encoder.py", line 258, in iterencode return _iterencode(o, 0) ^^^^^^^^^^^^^^^^^ File "/Users/karthik/anaconda3/lib/python3.11/json/encoder.py", line 180, in default raise TypeError(f'Object of type {o.**class**.**name**} ' TypeError: Object of type EmbeddingModel is not JSON serializable`
> 
> This error is because the enum I am using to select valid embedding models can't be expressed as JSON, so can't be sent as an API request. The `LLMModel` enum is JSON serializable because it also inherits from `str`, but the EmbeddingModel is a tuple of values.

What shall I do to solve this error? 

I assume new user's might face this problem when they use LLettuce and they might have not aware of the errors.

**Comment by kuraisle** [comment]
> What shall I do to solve this error?
> 
> I assume new user's might face this problem when they use LLettuce and they might have not aware of these errors.

Don't worry, I'm fixing it

**Comment by Karthi-DStech** [comment]
> > What shall I do to solve this error?
> > I assume new user's might face this problem when they use LLettuce and they might have not aware of these errors.
> 
> Don't worry, I'm fixing it

Alright James👍🏻

**Comment by Karthi-DStech** [comment]
Hi James, 

The scripts are working without throwing any errors. I'll approve the changes and merge them into the main. Good Job👏🏻

**Pull request merged**
