### PR TITLE
Feature/simple db multiple query

### LINKED ISSUE #12: 🐛 OMOP_match opens and closes multiple database connections
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When multiple names are fed to the pipeline, a database connection is opened and closed for each name. We should make it so the connection is opened, all the queries are processed, then the connection is closed.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS: MacOS
```

### I'm part of a Project Team

_No response_

### Anything else?

_No response_

### Are you willing to contribute to resolve this issue?

✅ Yes, me or my team intend to do the development.

### PR DESCRIPTION
**Pull request by kuraisle**
## Pull Request Contents

| |
|-|
♻️ Refactor
✨ Feature

## Description

I've modified OMOP_match so that OMOPMatcher.calculate_best_matches receives the list it was always meant to. This way, you can send a single API request, one connection is opened to the database, the queries are run, and the connection is closed.

I've changed the routes that use the database so the right format is used for OMOP queries. This doesn't work with the UI yet, but I'm keeping the PR small

## Related Issues or other material

- [X] This PR relates to one or more issues, detailed below

- Related Issue #12 
- Closes #12 

## ✅ Added/updated tests?

- [X] This PR contains relevant tests
  - Or doesn't need to per the below explanation

Added tests in the tests folder that check multiple queries return multiple results

- [X] I've completed all **actions** and **tasks** detailed in the PR Template

### CODE REVIEW

**Comment by Karthi-DStech** [comment]
Hi James, 

I tried to run the code and it closes the database connection as expected. But I can see, that it queries LLM directly and doesn't query the OMOP database with informal names before using the LLM. 

Are you going to add this feature in this commit or should I want to add that?

**Comment by kuraisle** [comment]
> Hi James,
> 
> I tried to run the code and it closes the database connection as expected. But I can see, that it queries LLM directly and doesn't query the OMOP database with informal names before using the LLM.
> 
> Are you going to add this feature in this commit or should I want to add that?

Hi Karthik,

To keep this to a single feature commit, let's add the other features separately. Did you try running the tests too? I thought it was pretty simple to set them up

**Comment by Karthi-DStech** [comment]
Ok James, let's implement the database login here and will create a new branch to implement the query first feature and an option to choose LLM in the GUI. I saw the test as well and it's working well. Good Job James👏🏻

**Comment by kuraisle** [comment]
> Ok James, let's implement the database login here and will create a new branch to implement the query first feature and an option to choose LLM in the GUI. I saw the test as well and it's working well. Good Job James👏🏻

Is there any need for me to change anything?

**Comment by Karthi-DStech** [comment]
Is the GUI portion of the code working, James? The last time I tried running it, I encountered an error related to Streamlit.

**Comment by kuraisle** [comment]
> Is the GUI portion of the code working, James? The last time I tried running it, I encountered an error related to Streamlit.

Nope, this breaks the GUI! I'll fix in another PR

**Comment by Karthi-DStech** [comment]
Alright James, I'll approve the PR.

**Pull request merged**
